version: "3"

services:
  app:
    build: .
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    working_dir: /app
    command: jupyter-notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    tty: true
