version: "3"
services:
  app:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./app:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    command: jupyter-notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    tty: true
  selenium:
    # see https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#experimental-mult-arch-aarch64armhfamd64-images
    image: seleniarm/standalone-chromium:121.0.6167.160
    environment:
      - SE_NODE_SESSION_TIMEOUT=${SESSION_TIMEOUT}
    ports:
      - 4444:4444
      - 7900:7900
