name: sample workflow

on:
  push:
  # schedule:
  #   - cron: '58 01 20 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python script
        run:  |
          cd app
          python app.py
        env:
          TZ: 'Asia/Tokyo'    
          SELENIUM_URL: http://localhost:4444/wd/hub

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: app/log
